In [13]:
import pandas as pd

df = pd.read_csv('623149_data.csv')
df

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp
0,FF,2023-09-27,93.0,-3.69,4.39,"Sewald, Paul",571980,623149,strikeout,swinging_strike,...,3,3,0,0,3,Standard,Standard,243.0,-0.016,-0.225
1,FF,2023-09-27,92.6,-3.67,4.45,"Sewald, Paul",571980,623149,NaN,swinging_strike,...,3,3,0,0,3,Standard,Standard,237.0,0.000,-0.071
2,FF,2023-09-27,93.3,-3.61,4.47,"Sewald, Paul",571980,623149,NaN,ball,...,3,3,0,0,3,Standard,Standard,241.0,0.000,0.023
3,FF,2023-09-27,93.4,-3.64,4.52,"Sewald, Paul",571980,623149,NaN,called_strike,...,3,3,0,0,3,Standard,Standard,242.0,0.000,-0.051
4,FF,2023-09-27,91.4,-3.64,4.48,"Sewald, Paul",672820,623149,double,hit_into_play,...,3,3,0,0,3,Standard,Standard,236.0,0.011,0.263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,FF,2023-03-30,91.2,-3.65,4.45,"Sewald, Paul",686823,623149,NaN,swinging_strike,...,0,0,0,0,0,Standard,Standard,241.0,0.000,-0.036
1033,FF,2023-03-30,92.4,-3.59,4.46,"Sewald, Paul",686823,623149,NaN,called_strike,...,0,0,0,0,0,Standard,Standard,265.0,0.000,-0.026
1034,FF,2023-03-30,90.7,-3.74,4.42,"Sewald, Paul",665926,623149,field_out,hit_into_play,...,0,0,0,0,0,Standard,Standard,245.0,0.046,-0.228
1035,ST,2023-03-30,81.9,-3.73,4.59,"Sewald, Paul",665926,623149,NaN,ball,...,0,0,0,0,0,Standard,Standard,93.0,0.000,0.028
1036,FF,2023-03-30,89.5,-3.73,4.46,"Sewald, Paul",665926,623149,NaN,called_strike,...,0,0,0,0,0,Standard,Standard,243.0,0.000,-0.038

In [29]:
df = df.sort_values(by = ['game_date','at_bat_number','pitch_number'], ascending=[True,True,True]).reset_index(drop=True)

uq_pitches = ['FF', 'ST']
first_pitch = []
first_zone = []
bat_count = []
this_batter = 0
count = 0
for pitch in df.index:
    if df['batter'][pitch] != this_batter:
        bat_count.append(count)
        count = 0
        this_batter = df['batter'][pitch]
        first_pitch.append(df['pitch_type'][pitch])
        first_zone.append(df['zone'][pitch])
        count += 1
    elif df['batter'][pitch] == this_batter:
        count += 1

uq_zones = list(set(first_zone))

for pitch in uq_pitches:
    print(pitch, first_pitch.count(pitch) / len(first_pitch), first_pitch.count(pitch))
    
print('')
for zone in uq_zones:
    print(zone, first_zone.count(zone) / len(first_zone), first_zone.count(zone))
    
sum(bat_count) / len(bat_count)

FF 0.5673469387755102 139
ST 0.4326530612244898 106

1 0.0326530612244898 8
2 0.04897959183673469 12
3 0.0163265306122449 4
4 0.11020408163265306 27
5 0.1306122448979592 32
6 0.07755102040816327 19
7 0.02040816326530612 5
8 0.07755102040816327 19
9 0.04897959183673469 12
11 0.1673469387755102 41
12 0.044897959183673466 11
13 0.05714285714285714 14
14 0.1673469387755102 41

4.216326530612245

In [17]:
df[df['batter'] == 608369] # corey seager at bats

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp
830,FF,2023-08-22,92.3,-3.57,4.45,"Sewald, Paul",608369,623149,NaN,ball,...,6,3,6,3,6,NaN,Standard,242.0,0.00,0.025
831,ST,2023-08-22,83.5,-3.72,4.47,"Sewald, Paul",608369,623149,NaN,swinging_strike,...,6,3,6,3,6,NaN,Standard,95.0,0.00,-0.031
832,FF,2023-08-22,91.2,-3.75,4.38,"Sewald, Paul",608369,623149,NaN,ball,...,6,3,6,3,6,NaN,Standard,228.0,0.00,0.034
833,FF,2023-08-22,92.4,-3.71,4.37,"Sewald, Paul",608369,623149,NaN,foul,...,6,3,6,3,6,NaN,Standard,239.0,0.00,-0.048
834,FF,2023-08-22,94.0,-3.74,4.37,"Sewald, Paul",608369,623149,NaN,ball,...,6,3,6,3,6,NaN,Standard,239.0,0.00,0.059
835,ST,2023-08-22,82.7,-3.67,4.45,"Sewald, Paul",608369,623149,walk,ball,...,6,3,6,3,6,NaN,Standard,94.0,-0.02,0.227

In [55]:
len(df[(df['zone'].isin([11, 12, 13, 14])) & (df['description'].isin(['called_strike', 'swinging_strike', 'foul']))]) \
/ len(df[df['zone'].isin([11, 12, 13, 14])])

len(df[(df['zone'].isin([11, 12, 13, 14])) & (df['description'].isin(['hit_into_play']))]) \
/ len(df[df['zone'].isin([11, 12, 13, 14])])

len(df[(df['zone'].isin([11, 12, 13, 14])) & (df['description'].isin(['hit_into_play'])) & (df['events'] == 'field_out')]) \
/ len(df[df['zone'].isin([11, 12, 13, 14])])

len(df[(df['zone'].isin([11, 12, 13, 14])) & (df['description'].isin(['hit_into_play']))]) \
/ len(df[df['zone'].isin([11, 12, 13, 14])])

a = len(df[(df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])) & (df['description'].isin(['hit_into_play'])) &
           (df['events'] == 'field_out')]) \
/ len(df[df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])])

b = len(df[(df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])) & (df['description'].isin(['hit_into_play']))]) \
/ len(df[df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])])

len(df[(df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])) & (df['description'].isin(['called_strike', 'swinging_strike', 'foul']))]) \
/ len(df[df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])])

len(df[(df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])) & (df['description'].isin(['called_strike', 'swinging_strike', 'foul']))]) \
/ len(df[df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])])

len(df[(df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])) & (df['events'].isin(['home_run']))]) \
/ len(df[df['zone'].isin([1, 2, 3, 4, 5, 6, 7, 8, 9])])

len(df[(df['zone'].isin([11, 12, 13, 14])) & (df['events'].isin(['home_run']))]) \
/ len(df[df['zone'].isin([11, 12, 13, 14])])

a / b

0.5675675675675677